services:
    deno-1.13.0:
        image: denoland/deno:alpine-1.13.0
        working_dir: /app
        environment:
            - APP_ENV=development
        volumes:
            - ../../:/app
        entrypoint: /bin/sh /app/etc/bin/start

    deno-1.14.2:
        image: denoland/deno:alpine-1.14.2
        working_dir: /app
        environment:
            - APP_ENV=development
        volumes:
            - ../../:/app
        entrypoint: /bin/sh /app/etc/bin/start