services:
    e2e:
        build: ./e2e
        volumes:
            - ./e2e:/app
        environment:
            - host=deno-latest:8080
        depends_on:
            - deno-latest

    deno-latest:
        image: denoland/deno:alpine-1.25.2
        working_dir: /app
        environment:
            - APP_ENV=development
        ports:
            - 8080:8080
        volumes:
            - ../../:/app
        entrypoint: /bin/sh /app/etc/bin/start