services:
    dev:
        build:
            context: ../..
            dockerfile: etc/docker/Dockerfile
        ports:
            - 8080:8080
        environment:
            - APP_ENV=development
            - REDIS_HOST=mabach-system-redis
        volumes:
            - ../../:/app

    test:
        build:
            context: ../..
            dockerfile: etc/docker/Dockerfile
        environment:
            - APP_ENV=testing
        volumes:
            - ../../:/app