export const EEvent = {
  API_ADD_ROUTE: "API_ADD_ROUTE",
  BEFORE_ROUTE: "BEFORE_ROUTE",
  BEFORE_REQUEST: "BEFORE_REQUEST",
  ROUTE_NOT_FOUND: "ROUTE_NOT_FOUND",
  AFTER_ROUTE_RESPONSE: "AFTER_ROUTE_RESPONSE",
  ROUTE_ERROR: "ROUTE_ERROR",
  CRITICAL_ERROR: "CRITICAL_ERROR",
};
